### ISSUE TITLE
爬虫设计，python3+scrapy

### ISSUE THREAD

**Issue by ka1i** [shabbyhouse418/ComprehensiveDesign#2]

**Comment by LJIJCJ** [comment]
列出你的详细计划

**Comment by ka1i** [comment]
爬虫需要提供搜索关键字，比如c++,然后程序会爬去与之相关的数据，幷爬去细节内容。

**Comment by MichaelTan9999** [comment]
那岂不是我们需要搞出很多关键词？

谭鸿瑞

在 2019年12月3日，上午10:49，ka1i <notifications@github.com> 写道：

﻿

爬虫需要提供搜索关键字，比如c++,然后程序会爬去与之相关的数据，幷爬去细节内容。

**Comment by ka1i** [comment]
YOU RIGHT

**Comment by ka1i** [comment]
![cv](https://user-images.githubusercontent.com/45752767/70027899-2f608880-15de-11ea-9780-a8d704032aaa.png)
简历可以，但是好像需要登录才能看到。
