### ISSUE TITLE
#开发难点

### ISSUE THREAD

**Issue by sitaocheng** [shabbyhouse418/ComprehensiveDesign#6]
1.	数据爬取问题
现有的招聘网站数据结构错综复杂，需求讨论后，我们确认了需要的几项基本数据结构。但是，难以确定使用哪一个具体的招聘网站，因为我们不清楚哪些网站拥有或者缺少我们需要的数据结构，且有许多网站中存在虚假招聘信息。
2.	算法选择问题
我们从网上搜索到相关的数据分析、数据处理论文。但具体的实现方法和组员找到的数据集难以联系，具体的方法主要有协同过滤算法（基于关联度）和基于相似度的算法。
协同过滤算法（基于相似度）主要基于之前企业的录用数据，学生的信息与之前企业录用者信息的相似度越高，录取概率越高。但是我们目前没有合适的方法爬取到企业录用的学生的基本情况，最多只能看到企业员工的毕业院校等基础信息。而基于关联度的算法则是建立在学生信息和企业要求关联度的基础上，关联度越高，则录用的概率越高。
3.	网络页面框架搭建问题
由于缺乏相关网页开发经验，我们小组最初难以确定如何去开发一个数据分析应用的网页前端。尝试摸索之后，我们分析出几个可行的网络框架如flask、Django等，并分配组员开始学习相关框架为后期数据接口的创建和连接做准备。
2.2 解决方案与可行性研究
（针对当前存在的问题，分析文献寻求解决方案）
1.	数据爬取问题

解决方案： 我们采用具体实践的方法，将现有的几个热门招聘网站的基本数据结构都爬取下来，并且对比他们的交集，最终提炼出几个我们认为最重要的数据结构。解决流程如图所示。
![image](https://user-images.githubusercontent.com/48174426/70291575-8486df00-1816-11ea-9bbb-6c72e4dae1f1.png)

关键代码：
2.	算法选择问题
解决方案： 由于协同过滤算法需要的数据我们无法爬取，但协同过滤算法在数据分析尤其是招聘这样的推荐类算法中有较好的运算结果和借鉴意义，我们决定在使用基于关联度和相似度算法的基础上，构造出基于关联度和相似度算法的我们自己的数据集。最后在此数据集的基础上，使用协同过滤算法，或者混合使用两种算法。
![Uploading image.png…]()

关键代码:

**Comment by ka1i** [comment]
第二个图片看不了，希望修复。 @StauskasCST

**Comment by sitaocheng** [comment]
![image](https://user-images.githubusercontent.com/48174426/70299392-bbb5ba00-182f-11ea-8fd8-c88d80e9701a.png)
OKK
